name: Gem Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and publish gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials

          TAG=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
          export GEM_VERSION=$(echo "$TAG" | sed -E 's/v(.*)/\1/')
          echo "GEM_VERSION: $GEM_VERSION"
          gem build rails_accordion.gemspec
          gem push rails_accordion-*.gem
